[package]
name = "packed_bools_tests"
version = "0.1.0"
authors = ["Cavey Cool <caveycool@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
packed_bools = { path = "../packed_bools" }